Vagrant.configure("2") do |config|

  # specify the base
  config.vm.box = "ubuntu/trusty64"

  # only share my "src" directory (does not carry through to box)
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ENV["SRC_DIR"] || ".", "/src", create: true

  # forward ssh agent
  config.ssh.forward_agent = true

  # virtualbox specific configuration
  config.vm.provider "virtualbox" do |v|
    v.cpus             = 2
    v.default_nic_type = "82543GC"
    v.memory           = 4096
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  # forward ports
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # provision the guest
  config.vm.provision :shell, inline: "apt-get update"
  config.vm.provision :shell, inline: "apt-get upgrade -y"
  config.vm.provision :shell, inline: "apt-get install -y build-essential gettext libexpat1-dev libgmp3-dev liblzma-dev libmysqlclient-dev libncurses5-dev libpcre3-dev libreadline6-dev libxml2-dev libxslt-dev libz-dev pkg-config tree"

  # actuall had to install these manually on the guest via: `wget -qc -O- $PATH | sh`
  config.vm.provision :shell, path: "https://gist.github.com/j1n3l0/b7d1dabe8a81fef9d2f9035f6ed17989/raw/c0dd420e612f890d538a822bcfb72cbaefd59794/emacs.sh",   privileged: false # emacs
  config.vm.provision :shell, path: "https://gist.github.com/j1n3l0/b7d1dabe8a81fef9d2f9035f6ed17989/raw/c0dd420e612f890d538a822bcfb72cbaefd59794/git.sh",     privileged: false # git
  config.vm.provision :shell, path: "https://gist.github.com/j1n3l0/b7d1dabe8a81fef9d2f9035f6ed17989/raw/c0dd420e612f890d538a822bcfb72cbaefd59794/go.sh",      privileged: false # go
  config.vm.provision :shell, path: "https://gist.github.com/j1n3l0/b7d1dabe8a81fef9d2f9035f6ed17989/raw/1c4433f713aa89b6a9d55c8fdc2f0adb7cfcfd06/openssl.sh", privileged: false # openssl
  config.vm.provision :shell, path: "https://gist.github.com/j1n3l0/b7d1dabe8a81fef9d2f9035f6ed17989/raw/d646e3cda8c1a84a246269237b2d4e6fbce1edd5/plenv.sh",   privileged: false # plenv
  config.vm.provision :shell, path: "https://gist.github.com/j1n3l0/b7d1dabe8a81fef9d2f9035f6ed17989/raw/c0dd420e612f890d538a822bcfb72cbaefd59794/ag.sh",      privileged: false # ag
  config.vm.provision :shell, path: "https://gist.github.com/j1n3l0/b7d1dabe8a81fef9d2f9035f6ed17989/raw/c0dd420e612f890d538a822bcfb72cbaefd59794/entr.sh",    privileged: false # entr
  config.vm.provision :shell, path: "https://gist.github.com/j1n3l0/b7d1dabe8a81fef9d2f9035f6ed17989/raw/c0dd420e612f890d538a822bcfb72cbaefd59794/direnv.sh",  privileged: false # direnv

  # clean up and save space
  config.vm.provision :shell, inline: "apt-get autoremove -y"
  config.vm.provision :shell, inline: "apt-get clean"

end
