Vagrant.configure("2") do |config|

  # specify the base
  config.vm.box = "ubuntu/trusty64"

  # only share my "src" directory (does not carry through to box)
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ENV["SRC_DIR"] || ".", "/src", create: true

  # forward ssh agent
  config.ssh.forward_agent = true

  # virtualbox specific configuration
  config.vm.provider "virtualbox" do |v|
    v.cpus             = 2
    v.default_nic_type = "82543GC"
    v.memory           = 4096
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  # forward ports
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # provision the guest
  config.vm.provision :shell, inline: "apt-get update"
  config.vm.provision :shell, inline: "apt-get upgrade -y"
  config.vm.provision :shell, inline: "apt-get install -y build-essential gettext libexpat1-dev libgmp3-dev liblzma-dev libmysqlclient-dev libncurses5-dev libpcre3-dev libreadline6-dev libxml2-dev libxslt-dev libz-dev pkg-config tree"

  # clean up and save space
  config.vm.provision :shell, inline: "apt-get autoremove -y"
  config.vm.provision :shell, inline: "apt-get clean"

end
